# Generated by Django 4.0.4 on 2022-05-01 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='static\x07ssets\\img'),
        ),
    ]
